export const profile = {
  name: 'Talha Alam',
  shortName: 'TA',
  role: 'Electronics Engineer · AI Hardware',
  location: 'KPK, Pakistan',
  email: 'talhaalame.e@gmail.com',
  phone: '+92 349 9530896',
  education: 'B.Sc. Electronics Engineering · UET Peshawar · 2022–2026',
  headline: 'I design the hardware behind efficient AI.',
  subhead: 'Digital VLSI, low-precision accelerators, and complete RTL-to-GDSII systems — with the model, microarchitecture, and physical design considered together.',
  links: {
    github: 'https://github.com/talha-ee',
    linkedin: 'https://www.linkedin.com/in/talhaalam-e-e/',
    scholar: 'https://scholar.google.com/citations?user=Ue74-00AAAAJ&hl=en',
    orcid: 'https://orcid.org/0009-0007-6627-4601',
    researchgate: 'https://www.researchgate.net/profile/Talha-Alam-3',
  },
}

export const proofPoints = [
  { value: 'RTL → GDSII', label: 'design range' },
  { value: 'AI + VLSI', label: 'working intersection' },
  { value: '45–130 nm', label: 'flow experience' },
]

export const projects = [
  {
    id: 'accelclosure',
    index: '01',
    year: '2026',
    kind: 'Research system',
    title: 'AccelClosure',
    deck: 'An agentic prompt-to-GDS framework for AI accelerator exploration.',
    summary: 'Turning an architecture brief into reproducible RTL, synthesis, physical design, and measured PPA evidence on an open process.',
    detail: 'AccelClosure generated, verified, and physically closed three square weight-stationary INT8 systolic arrays on Sky130HD: 4×4, 8×8, and 16×16. The framework keeps architecture choices, generated RTL, constraints, implementation reports, real-model workload checks, and the final GDSII artifacts connected in one evidence loop.',
    metric: '4×4 · 8×8 · 16×16',
    metricLabel: 'physically closed WS INT8 arrays',
    secondary: [
      ['210.57 / 212.00 / 208.18 MHz', 'post-route Fmax estimates'],
      ['0.121669 / 0.505428 / 1.890364 mm²', 'routed area · 4×4 / 8×8 / 16×16'],
      ['0.0795 / 0.3570 / 1.2800 W', 'vectorless power · 4×4 / 8×8 / 16×16'],
    ],
    tags: ['Sky130HD', 'INT8', 'Weight-stationary', 'OpenROAD'],
    note: 'All three references are routed WS INT8 implementations with zero reported setup and hold violations and generated GDS artifacts. GDS generation is implementation evidence, not foundry signoff or tapeout readiness.',
    links: [{ label: 'AccelClosure repository', href: 'https://github.com/talha-ee/AccelClosure' }, { label: 'Project post', href: 'https://lnkd.in/p/dGeVrmcd' }, { label: 'Process video', href: 'https://drive.google.com/file/d/19LnPHSbR9CwAAQcNPCljX5z2CDBLNB2w/view?usp=sharing' }],
    figureImages: [
      { src: './figures/accelclosure/4x4-gds.png', label: '4×4 · post-route GDSII', alt: '4 by 4 AccelClosure systolic array GDSII layout in KLayout', caption: '4×4 WS INT8 reference · 210.57 MHz estimated Fmax · 0.121669 mm² routed area.' },
      { src: './figures/accelclosure/8x8-gds.png', label: '8×8 · post-route GDSII', alt: '8 by 8 AccelClosure systolic array GDSII layout in KLayout', caption: '8×8 WS INT8 reference · 212.00 MHz estimated Fmax · 0.505428 mm² routed area.' },
      { src: './figures/accelclosure/16x16-gds.png', label: '16×16 · post-route GDSII', alt: '16 by 16 AccelClosure systolic array GDSII layout in KLayout', caption: '16×16 WS INT8 reference · 208.18 MHz estimated Fmax · 1.890364 mm² routed area.' },
    ],
    workload: {
      title: 'Real Transformer tensors, software-tiled across every array',
      detail: 'The workload evaluation uses actual trained weights and real activations from three public Transformer models. The selected GEMM tiles were executed with INT8 operands and INT32-compatible accumulation across the 4×4, 8×8, and 16×16 candidates.',
      rows: [
        ['TinyBERT-4L-312D', '16 × 312 × 64', '0.993507'],
        ['TinyLlama-1.1B', '16 × 2048 × 64', '0.997716'],
        ['Qwen2.5-1.5B', '16 × 1536 × 64', '0.992100'],
      ],
      footnote: 'Exact INT32 across all three array sizes: PASS. Cosine similarity shown after the symmetric INT8 quantization experiment.',
    },
    visual: 'accel',
    categories: ['AI', 'ASIC', 'Research'],
  },
  {
    id: 'gemmini',
    index: '02',
    year: '2026',
    kind: 'Thesis · accelerator architecture',
    title: 'Extending Gemmini DNN Accelerator for transformer workloads',
    deck: 'A multiplier-optimized INT8 systolic array, taken from arithmetic redesign through Gemmini integration and 45 nm GDSII.',
    summary: 'Redesigning the multiplier at the arithmetic level, integrating it into the Gemmini processing element, and scaling the result into larger MOSA systolic arrays while preserving Weight Stationary and Output Stationary dataflows.',
    detail: 'The proposed INT8 multiplication architecture uses Radix-4 Booth encoding with an optimized compressor reduction structure to reduce multiplication hardware and shorten the critical computation path. I developed and evaluated the hierarchy at 8×8, 16×16, and 32×32 multiplier levels, integrated it through the Gemmini PE and mesh hierarchy in Chipyard, and then implemented the proposed 16×16 Multiplier Optimized Systolic Array (MOSA) through Cadence Genus and Innovus on GPDK045 45 nm technology.',
    metric: '13.49%',
    metricLabel: 'area reduction · 16×16 Gemmini MOSA',
    secondary: [
      ['20.96 / 25.19 / 25.18%', 'multiplier area reduction · 8×8 / 16×16 / 32×32'],
      ['38.87%', '32×32 multiplier delay improvement'],
      ['13.49 / 13.49 / 12.14%', 'Gemmini array area reduction · 16×16 / 32×32 / 64×64'],
      ['1.217 mm²', '16×16 MOSA GDSII footprint · GPDK045'],
      ['66.79%', 'placement density · 320,288 instances'],
    ],
    tags: ['Gemmini', 'Radix-4 Booth', 'Cadence Genus + Innovus', 'GPDK045 · 45 nm', 'WS + OS'],
    note: 'The multiplier and Gemmini array percentages are hierarchical comparisons against the baseline. The 1.217 mm², 1103.4 µm × 1103.14 µm, 66.79% density, and 320,288-instance values describe the proposed 16×16 MOSA physical implementation on GPDK045; they are implementation evidence, not fabricated-silicon measurements.',
    links: [{ label: 'Gemmini / Chipyard repo', href: 'https://github.com/talha-ee/Chipyard-1.9.1-with-RISC-V-Toolchains' }, { label: 'GitHub profile', href: profile.links.github }],
    figureImages: [
      { src: './figures/gemmini/16x16-mosa-gds.png', label: '16×16 MOSA · complete GDSII', alt: 'Complete 16 by 16 Multiplier Optimized Systolic Array GDSII layout', caption: 'Complete proposed 16×16 MOSA physical implementation · approximately 1.217 mm² · GPDK045 45 nm.' },
      { src: './figures/gemmini/memory-instance-detail.png', label: 'Memory instance · routed detail', alt: 'Zoomed routed Gemmini memory instance in the GDSII layout', caption: 'Routed physical-design detail showing the memory instance region inside the Gemmini implementation.' },
      { src: './figures/gemmini/16x16-pe-detail.png', label: '16×16 PE · routed detail', alt: 'Zoomed 16 by 16 processing element region in the GDSII layout', caption: 'Zoomed 16×16 PE region from the proposed multiplier-optimized systolic array.' },
    ],
    resultTables: [
      { title: 'Multiplier hierarchy', columns: ['Configuration', 'Area reduction', 'Delay'], rows: [['8×8 multiplier', '20.96%', '—'], ['16×16 multiplier', '25.19%', '—'], ['32×32 multiplier', '25.18%', '38.87% improvement']] },
      { title: 'Gemmini MOSA integration', columns: ['Array', 'Area reduction', 'Dataflow support'], rows: [['16×16', '13.49%', 'WS + OS'], ['32×32', '13.49%', 'WS + OS'], ['64×64', '12.14%', 'WS + OS']] },
    ],
    physicalRecord: [['GDSII footprint', '≈ 1.217 mm²'], ['Die / block dimensions', '1103.4 µm × 1103.14 µm'], ['Placement density', '66.79%'], ['Physical instances', '320,288']],
    visual: 'gemmini',
    categories: ['AI', 'ASIC', 'Research'],
  },
  {
    id: 'nce',
    index: '03',
    year: '2026',
    kind: 'Mixed-precision compute',
    title: 'Neural Compute Engine',
    deck: 'A tapeout-ready mixed-precision neural compute accelerator, carried from RTL to chip-level GDSII.',
    summary: 'One of my largest hardware builds: a full multi-precision accelerator developed from architectural design and RTL through verification, physical implementation, and final chip assembly.',
    detail: 'The NCE supports bfloat16, bfloat24, and packed INT8 operations with dedicated FP32 accumulation for numerical accuracy. Its mixed-precision MACs, systolic processing structures, tiled GEMM engine, register files, control logic, and AXI4-Lite interface were taken through synthesis, floorplanning, placement, clock-tree synthesis, routing, hard-macro generation, chip-level IO integration, power-grid construction, density fill, and final GDSII assembly using LibreLane and OpenROAD on Sky130.',
    metric: '62 / 62',
    metricLabel: 'verification suites passed',
    secondary: [
      ['8.2 × 8.2 mm', 'chip die · Sky130'],
      ['6.525 × 6.525 mm', 'hardened accelerator core'],
      ['154 + 16', 'signal GPIO + power / ground pads'],
      ['1.044 m', 'routed interconnect'],
      ['0', 'detailed-routing violations'],
    ],
    tags: ['Sky130', 'LibreLane + OpenROAD', 'BF16 / BF24', 'INT8 + FP32', 'AXI4-Lite'],
    note: 'The core was hardened first, then integrated into a complete chip wrapper with pad-to-core routing, VCCD / VSSD power connectivity, four corner cells, an IO filler ring, metal-density fill, and final GDSII assembly. These are tapeout-ready implementation results, not fabricated-silicon measurements or foundry signoff.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7490874114795048962/' }],
    figureImages: [
      { src: './figures/nce/nce-chip-top-gds.png', type: 'GDSII / KLAYOUT', label: 'Chip top · complete GDSII', alt: 'Complete Neural Compute Engine chip-level GDSII layout', caption: 'Complete 8.2 mm × 8.2 mm chip-level GDSII assembled with LibreLane / OpenROAD on Sky130.' },
      { src: './figures/nce/nce-chip-top-branded.png', type: 'CHIP TOP / KLAYOUT', label: 'NCE chip top · branded view', alt: 'Branded Neural Compute Engine chip top layout in KLayout', caption: 'Top-level NCE wrapper with the accelerator core, pad ring, IO fillers, and chip-level integration visible.' },
      { src: './figures/nce/nce-core-macro.png', type: 'HARD MACRO / KLAYOUT', label: 'Accelerator core · hardened macro', alt: 'Neural Compute Engine hardened accelerator core macro in KLayout', caption: 'The independently hardened accelerator core before chip-wrapper integration.' },
      { src: './figures/nce/verification-regression.png', type: 'REGRESSION / VERIFICATION', label: 'Post-test regression · 62 / 62 PASS', alt: 'Neural Compute Engine post-test verification regression showing all suites passing', caption: 'Post-test verification record: 62 suites executed, 62 passed, 0 failed.' },
    ],
    resultTables: [
      { title: 'Chip-level physical record', columns: ['Metric', 'Result', 'Scope'], rows: [['Die size', '8.2 × 8.2 mm', 'Sky130 chip top'], ['Total die area', '67.24 mm²', 'complete chip'], ['Accelerator core', '6.525 × 6.525 mm', '42.58 mm² hardened core'], ['Signal IO', '154 GPIO', 'plus 16 power / ground pads'], ['Routed interconnect', '1.044 m', 'final assembly'], ['Detailed-route DRC', '0 violations', 'final chip']] },
      { title: 'Verification record', columns: ['Regression', 'Result', 'Evidence'], rows: [['Complete design regression', '62 / 62', '0 failed'], ['AXI4-Lite interface', '1,006 transactions', 'control-path validation'], ['Mixed precision', 'PASS', 'INT8 / BF16 / BF24 / FP32']] },
    ],
    physicalRecord: [['Die / chip top', '8.2 mm × 8.2 mm'], ['Total die area', '67.24 mm²'], ['Accelerator core', '6.525 mm × 6.525 mm'], ['Hardened core area', '42.58 mm²'], ['IO ring', '154 GPIO + 16 power / ground'], ['Corners / filler', '4 corner cells + complete IO filler ring'], ['Routed interconnect', '1.044 m'], ['Detailed-route DRC', '0 violations']],
    visual: 'nce',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'transformer',
    index: '04',
    year: '2026',
    kind: 'Transformer inference',
    title: 'INT4 Attention Systolic Array Accelerator',
    deck: 'A 16×16 INT4 Transformer attention accelerator with fixed-point softmax, systolic GEMM, and an 8-bit memory-mapped wrapper.',
    summary: 'A tile-based attention engine validated against real GPT-2, distilgpt2, and TinyBERT tensors, with the RTL core, wrapper, software comparison, and synthesis evidence kept as separate measurements.',
    detail: 'I completed pre-synthesis RTL validation of a 16×16 INT4 attention accelerator with Q/K/V matrix multiplication, fixed-point softmax, P·V and Wₒ projection, and an 8-bit memory-mapped wrapper. Across 62 real-model attention-tile cases, the fixed-point RTL matched the golden model with zero mismatches: 14 GPT / distilgpt2 cases and 48 TinyBERT cases. The standalone RTL core takes 913 cycles per tile; the full wrapper path takes 2,210 cycles. A separate Cadence Genus synthesis run on GPDK045 45 nm reports the implementation-level PPA snapshot below.',
    metric: '6.821 GOPS',
    metricLabel: 'synthesis-level INT4 throughput',
    secondary: [
      ['62 / 62', 'real-model tiles · PASS'],
      ['333.33 MHz', 'Cadence · GPDK045 45 nm'],
      ['0.62782 mm²', 'mapped area · 286,546 cells'],
      ['74.4808 mW', 'synthesis-level power'],
      ['268.35 nJ', 'energy per 16×16 tile'],
    ],
    tags: ['INT4', 'Systolic GEMM', 'Cadence Genus', 'GPDK045 · 45 nm', 'PicoRV32 wrapper'],
    note: 'The 913-cycle result is the standalone RTL core; 2,210 cycles is the full 8-bit wrapper path; 56.1× and 23.2× are separate comparisons against the RISC-V software baseline. The Cadence Genus / GPDK045 values are synthesis-level implementation evidence, not a routed layout or fabricated-silicon measurement.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7476597886139555840/' }],
    figureImages: [
      { src: './figures/transformer/riscv-benchmark.jpeg', type: 'CYCLE BENCHMARK', label: 'RISC-V vs RTL · 56.1× core', alt: 'RISC-V software versus RTL accelerator cycle benchmark for a real INT4 attention tile', caption: 'Measured comparison for a real 16×16 INT4 attention tile: 51,231 software cycles versus 913 RTL core cycles, an estimated 56.1× core-cycle reduction.' },
      { src: './figures/transformer/tinybert-validation.png', type: 'RTL VALIDATION', label: 'TinyBERT · 48 / 48 PASS', alt: 'TinyBERT real-model INT4 attention tile validation log with all cases passing', caption: 'TinyBERT self-attention validation: 48 PASS, 0 FAIL, with 913 RTL core cycles per tile.' },
      { src: './figures/transformer/gpt2-validation.jpeg', type: 'RTL VALIDATION', label: 'GPT / distilgpt2 · 14 / 14 PASS', alt: 'GPT-2 and distilgpt2 real-model INT4 attention tile validation log with all cases passing', caption: 'GPT-2 and distilgpt2 validation: 14 PASS, 0 FAIL, with the functional checksum and 913-cycle core result retained.' },
    ],
    resultTables: [
      { title: 'Real-model RTL validation', columns: ['Workload set', 'Result', 'Scope'], rows: [['GPT-2 + distilgpt2', '14 PASS / 0 FAIL', 'real 16×16 attention tiles'], ['TinyBERT', '48 PASS / 0 FAIL', 'real self-attention tiles'], ['Total', '62 PASS / 0 FAIL', 'zero golden-model mismatches'], ['RTL core latency', '913 cycles', 'standalone accelerator'], ['Wrapper latency', '2,210 cycles', 'full 8-bit MMIO path'], ['RISC-V comparison', '56.1× / 23.2×', 'core / full wrapper cycle reduction']] },
      { title: 'Cadence / GPDK045 synthesis snapshot', columns: ['Metric', 'Frozen value', 'Scope'], rows: [['Technology', 'GPDK045 · 45 nm', 'Cadence Genus'], ['Accelerator', 'attention_mmio32_native_wrapper_16x16_int4', 'mapped wrapper'], ['Cell count', '286,546', 'mapped cells'], ['Mapped cell area', '0.62782 mm²', 'synthesis result'], ['Clock period', '3.000 ns', '333.33 MHz'], ['Critical datapath', '2.782 ns', '+91 ps setup slack'], ['Power', '74.4808 mW', 'vectorless synthesis estimate']] },
      { title: 'Performance and energy record', columns: ['Metric', 'Value', 'Definition'], rows: [['Tile cycles', '1,201 cycles', 'Cadence power-activity run'], ['Tile latency', '3.603 µs', 'at 333.33 MHz'], ['Work / tile', '12,288 MACs', 'QKᵀ + fixed-point softmax + P·V + Wₒ'], ['Throughput', '3.410 GMAC/s', 'per accelerator tile'], ['Performance', '6.821 GOPS', '2 operations per MAC'], ['PDP', '207.21 pJ', 'area × critical delay'], ['ADP', '1.7466 mm²·ns', 'mapped area × clock period'], ['GOPS / W', '91.58', 'performance / power'], ['GOPS / mm²', '10.86', 'performance / mapped area'], ['Energy / tile', '268.35 nJ', '74.4808 mW × 3.603 µs'], ['Energy / MAC', '21.84 pJ', 'energy / 12,288 MACs'], ['Energy / operation', '10.92 pJ', 'energy / 24,576 ops'], ['Checksum', '0xe20c75cf · PASS', 'functional equivalence']] },
    ],
    physicalRecord: [['Technology', 'GPDK045 · 45 nm'], ['Mapped cell area', '0.62782 mm²'], ['Mapped cells', '286,546'], ['Clock / Fmax', '3.000 ns · 333.33 MHz'], ['Critical datapath', '2.782 ns'], ['Setup slack', '+91 ps'], ['Power', '74.4808 mW'], ['Energy / tile', '268.35 nJ']],
    visual: 'attention',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cnn-tapeout',
    index: '05',
    year: '2026',
    kind: 'ASIC · biomedical edge AI',
    title: 'Tiny 1D-CNN, all the way to GDSII',
    deck: 'A 16-PE 1D-CNN systolic accelerator taken through Cadence Genus, Innovus, post-route closure, and GDSII at GPDK045 45 nm.',
    summary: 'A complete edge-AI datapath—from exact signed INT4 arithmetic and a pipelined MAC to a weight-stationary 1D systolic array—closed through physical implementation.',
    detail: 'The CNN_Tapeout accelerator uses an exact signed INT4×INT4 Baugh–Wooley multiplier with complemented sign terms, LAS 3:2/4:2 compressor reduction, and a pipelined MAC. Sixteen processing elements form a one-dimensional MOSA / activation-systolic array with stationary weights, delayed activation and valid propagation, ping-pong activation storage, requantization, ReLU, signed-INT4 saturation, and layer sequencing. I carried the design from RTL synthesis through placement, clock-tree synthesis, routing, post-route timing closure, and GDSII generation using Cadence Genus and Innovus on GPDK045 45 nm.',
    metric: '0.164 mm²',
    metricLabel: 'routed core area · GPDK045',
    secondary: [
      ['166.67 MHz', 'post-route operating point'],
      ['64.227%', 'placement density'],
      ['+0.200 ns', 'setup WNS'],
      ['+0.192 ns', 'hold WNS'],
      ['0', 'setup / hold / DRC violations'],
    ],
    tags: ['INT4', '1D-CNN', 'Cadence Genus + Innovus', 'GPDK045 · 45 nm', 'Systolic array'],
    note: 'The final routed core reports clean setup, hold, transition, capacitance, and antenna checks: setup WNS +0.200 ns, hold WNS +0.192 ns, and zero violations in each category. These are post-route implementation results, not fabricated-silicon measurements or foundry signoff.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478525419974086656/' }],
    figureImages: [
      { src: './figures/cnn-tapeout/cnn-core-gds.png', type: 'GDSII / KLAYOUT', label: 'Routed core · complete GDSII', alt: 'Complete routed Tiny 1D-CNN accelerator core GDSII layout in KLayout', caption: 'Complete post-route core view of the 16-PE 1D-CNN systolic accelerator in GPDK045 45 nm.' },
      { src: './figures/cnn-tapeout/cnn-routed-detail.png', type: 'POST-ROUTE / KLAYOUT', label: 'Routed core · physical detail', alt: 'Detailed routed Tiny 1D-CNN accelerator layout view', caption: 'Detailed routed implementation view showing the dense accelerator core and physical interconnect.' },
      { src: './figures/cnn-tapeout/cnn-chip-top.png', type: 'CHIP TOP / KLAYOUT', label: 'Chip top · GPDK045', alt: 'Tiny 1D-CNN accelerator chip top with pad ring and GPDK045 branding', caption: 'Top-level implementation view with the routed core, pad ring, and GPDK045 technology marker.' },
    ],
    resultTables: [
      { title: 'Post-route closure record', columns: ['Metric', 'Result', 'Scope'], rows: [['Technology', 'GPDK045 · 45 nm', 'Cadence Genus + Innovus'], ['Core area', '0.164 mm²', 'routed core'], ['Placement density', '64.227%', 'final placement'], ['Setup WNS', '+0.200 ns', 'post-route timing'], ['Hold WNS', '+0.192 ns', 'post-route timing'], ['Setup / hold violations', '0', 'clean closure'], ['Max transition violations', '0', 'design-rule check'], ['Max capacitance violations', '0', 'design-rule check'], ['Antenna violations', '0', 'signoff check']] },
      { title: 'RTL-to-GDSII architecture', columns: ['Block', 'Implementation', 'Role'], rows: [['INT4 multiplier', 'Exact signed Baugh–Wooley', 'signed 4×4 partial products'], ['Reduction tree', 'LAS 3:2 + LAS 4:2', 'compressor-based accumulation'], ['MAC / PE', 'Pipelined, weight-stationary', 'registered product-sum'], ['Array', '16-PE 1D MOSA', 'activation-systolic flow'], ['Output path', 'Requantize → ReLU → saturate', 'signed INT4 layer output']] },
    ],
    physicalRecord: [['Technology', 'GPDK045 · 45 nm'], ['Flow', 'Cadence Genus + Innovus'], ['Routed core area', '0.164 mm²'], ['Placement density', '64.227%'], ['Setup WNS', '+0.200 ns'], ['Hold WNS', '+0.192 ns'], ['Max transition / capacitance', '0 violations'], ['Antenna violations', '0']],
    visual: 'cnn',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cgm-asic',
    index: '06',
    year: '2026',
    kind: 'ASIC · low-power biomedical',
    title: 'High-performance Tiny 1D-CNN ASIC',
    deck: 'A streaming line-buffer 1D-CNN accelerator taken from Python and quantized inference through SKY130 RTL-to-GDSII implementation.',
    summary: 'A complete biomedical edge-AI path for real-time continuous glucose monitoring: software model, Verilog datapath, streaming memory architecture, physical implementation, and final GDSII layout.',
    detail: 'The accelerator began with a software 1D-CNN for glucose-level prediction and was translated into a hardware architecture using fully partitioned shift registers and a streaming line-buffer dataflow. The Verilog design was synthesized and physically implemented with LibreLane, Yosys, OpenROAD, and KLayout on the SkyWater 130 nm open-source PDK. The result is an approximately 944k-instance ASIC implementation with a 21.95 mm² die and clean reported timing and layout checks.',
    metric: '21.95 mm²',
    metricLabel: 'SKY130 die area · ≈944k instances',
    secondary: [
      ['944,036', 'standard-cell instances'],
      ['21.7%', 'core utilization'],
      ['5.05 ns', 'worst-case setup slack'],
      ['215.8 mW', 'nominal total power'],
      ['2.53 mV', 'maximum IR drop'],
    ],
    tags: ['SKY130 · 130 nm', 'LibreLane', 'OpenROAD', 'Streaming line buffer', 'CGM'],
    note: 'The reported implementation achieved timing closure with zero setup and hold violations and passed DRC and LVS checks. The 944,036 instances, 21.7% utilization, 21.95 mm² die, 5.05 ns slack, 215.8 mW nominal power, and 2.53 mV maximum IR drop are open-flow implementation results, not fabricated-silicon measurements or foundry signoff.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478525419974086656/' }, { label: 'GitHub profile', href: profile.links.github }],
    figureImages: [
      { src: './figures/cgm-asic/cgm-asic-gds.jpeg', type: 'GDSII / KLAYOUT', label: 'Tiny 1D-CNN · final GDSII', alt: 'Final SkyWater 130 nm Tiny 1D-CNN ASIC GDSII layout', caption: 'Final physical layout of the streaming Tiny 1D-CNN ASIC, showing the routed accelerator core and implementation boundary on SKY130.' },
    ],
    resultTables: [
      { title: 'SKY130 physical implementation', columns: ['Metric', 'Result', 'Scope'], rows: [['Technology', 'SkyWater 130 nm · SKY130', 'LibreLane / OpenROAD'], ['Flow', 'RTL → synthesis → place / route → GDSII', 'open-source ASIC flow'], ['Standard-cell instances', '944,036', 'reported implementation'], ['Core utilization', '21.7%', 'final floorplan'], ['Die area', '21.95 mm²', 'SKY130 physical footprint'], ['Worst-case setup slack', '5.05 ns', 'timing closure'], ['Nominal total power', '215.8 mW', 'reported estimate'], ['Maximum IR drop', '2.53 mV', 'power-integrity report']] },
      { title: 'Closure and verification', columns: ['Check', 'Result', 'Scope'], rows: [['Setup violations', '0', 'final timing'], ['Hold violations', '0', 'final timing'], ['DRC', 'PASS', 'physical design rules'], ['LVS', 'PASS', 'layout-versus-schematic'], ['Architecture', 'Streaming line buffer', 'fully partitioned shift registers'], ['Application', 'Real-time CGM inference', 'biomedical edge AI']] },
      { title: 'Python-to-GDSII path', columns: ['Stage', 'Artifact', 'Tool / method'], rows: [['Model development', '1D-CNN glucose predictor', 'Python / PyTorch'], ['Quantization', 'INT8 inference model', 'static quantization'], ['Hardware mapping', 'Verilog streaming datapath', 'line buffer + shift registers'], ['Physical implementation', 'placed and routed ASIC core', 'LibreLane / Yosys / OpenROAD'], ['Layout inspection', 'final GDSII evidence', 'KLayout']] },
    ],
    physicalRecord: [['Technology', 'SkyWater 130 nm · SKY130'], ['Flow', 'LibreLane → Yosys → OpenROAD'], ['Die area', '21.95 mm²'], ['Standard-cell instances', '944,036'], ['Core utilization', '21.7%'], ['Worst-case setup slack', '5.05 ns'], ['Nominal total power', '215.8 mW'], ['DRC / LVS', 'PASS / PASS']],
    visual: 'physical',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cnn-gpd045',
    index: '07',
    year: '2026',
    kind: 'ASIC · physical design',
    title: 'CNN systolic array accelerator',
    deck: 'A compact 45 nm implementation with timing and physical checks closed.',
    summary: 'Designed, synthesized, placed, routed, and checked as a complete GPDK045 RTL-to-GDSII exercise.',
    detail: 'The implementation uses a systolic array for convolutional workloads and was taken through Cadence Genus and Innovus. The physical report closes timing and common physical checks for the reported core.',
    metric: '166.7 MHz',
    metricLabel: 'closed implementation frequency',
    secondary: [
      ['0.164 mm²', 'core area'],
      ['64.227%', 'core density'],
      ['0', 'setup / hold / antenna violations'],
    ],
    tags: ['GPDK045', 'Genus', 'Innovus', 'Systolic array'],
    note: 'Reported implementation evidence from the 45 nm flow; it is not a fabricated-chip measurement.',
    links: [{ label: 'GitHub profile', href: profile.links.github }],
    visual: 'physical',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'tiny-cnn',
    index: '08',
    year: '2026',
    kind: 'FPGA · model-to-hardware',
    title: 'Streaming line-buffer CNN',
    deck: 'A dataflow-optimized Tiny 1D-CNN that keeps the window moving and the DSP budget at zero.',
    summary: 'Connecting PyTorch quantization to a streaming Artix-7 implementation with loop unrolling, pipelining, and a sliding-window buffer.',
    detail: 'The accelerator was developed with Vitis HLS and Vivado for real-time glucose prediction research. The microarchitecture removes DSP usage, improves the data path, and keeps the model-to-hardware assumptions explicit.',
    metric: '3×',
    metricLabel: 'latency improvement',
    secondary: [
      ['0', 'DSP blocks'],
      ['21%', 'reported power reduction'],
      ['Artix-7', 'target FPGA'],
    ],
    tags: ['Vitis HLS', 'Vivado', 'INT8', 'Dataflow'],
    note: 'The 3× and 21% figures are reported research results for the streaming implementation.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478055241054212096/' }],
    visual: 'stream',
    categories: ['AI', 'FPGA'],
  },
  {
    id: 'fpga-cgm',
    index: '09',
    year: '2026',
    kind: 'FPGA · edge inference',
    title: 'INT8 1D-CNN on Arty S7-35T',
    deck: 'A quantized Tiny 1D-CNN inference IP built with Vitis HLS and integrated in Vivado for the Arty S7-35T.',
    summary: 'The complete model-to-hardware path: INT8 quantization, C/RTL verification, HLS-generated RTL/IP, and post-implementation validation on an accessible Artix-7 FPGA.',
    detail: 'I implemented an INT8 quantized Tiny 1D-CNN inference design, generated synthesizable RTL and an HLS IP block with Vitis HLS, and integrated the result in Vivado for the Arty S7-35T. The datapath, control handshake, input/output buffers, and model assumptions were verified together, including representative quantized outputs and softmax probabilities. Post-implementation reports close timing while keeping the resource footprint compact for edge-AI inference.',
    metric: '3,953 LUTs',
    metricLabel: 'post-implementation resource footprint',
    secondary: [
      ['4,506', 'flip-flops'],
      ['42', 'DSP blocks'],
      ['33', 'BRAMs'],
      ['13.606 ns', 'post-implementation clock period'],
      ['≈ 3 mW', 'total on-chip power'],
    ],
    tags: ['Arty S7-35T', 'Vitis HLS', 'Vivado', 'INT8', 'TinyML'],
    note: 'The final Vivado report targets xc7a35t-csg324-1 and shows timing met at a 13.606 ns achieved post-implementation period. Resource and ≈3 mW power values refer to this FPGA build; they are not ASIC area or fabricated-silicon measurements.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478055241054212096/' }],
    figureImages: [
      { src: './figures/fpga-cgm/vivado-hls-ip-block.png', type: 'IP / VIVADO', label: 'Tiny1DCNN · generated IP block', alt: 'Vivado block design showing the generated Tiny1DCNN inference IP', caption: 'Generated Tiny1DCNN inference IP with clock, reset, control handshake, input streams, and output ports exposed for Vivado integration.' },
      { src: './figures/fpga-cgm/vivado-implementation-report.png', type: 'POST-IMPLEMENTATION', label: 'Vivado · timing and resources', alt: 'Vivado post-implementation resource and timing report for Arty S7-35T', caption: 'Post-implementation Vivado report: 3,953 LUTs, 4,506 FFs, 42 DSPs, 33 BRAMs, and timing met.' },
      { src: './figures/fpga-cgm/tinycnn-verification-a.png', type: 'C/RTL VERIFICATION', label: 'Functional verification · PASS', alt: 'Tiny1DCNN quantized output and softmax probability functional verification passing', caption: 'Representative quantized inference check with INT8 outputs, softmax probabilities, predicted class, and functional verification passed.' },
      { src: './figures/fpga-cgm/tinycnn-verification-b.png', type: 'C/RTL VERIFICATION', label: 'Second inference · PASS', alt: 'Second Tiny1DCNN quantized output and softmax probability verification passing', caption: 'Second representative INT8 inference check, again matching the expected class with functional verification passed.' },
      { src: './figures/fpga-cgm/hls-synthesis-report.png', type: 'HLS SYNTHESIS', label: 'Vitis HLS · 55.74 MHz est. Fmax', alt: 'Vitis HLS synthesis report showing satisfied loop constraints and estimated Fmax', caption: 'Vitis HLS synthesis completed successfully with all loop constraints satisfied and an estimated 55.74 MHz Fmax.' },
    ],
    resultTables: [
      { title: 'Vivado post-implementation record', columns: ['Resource / check', 'Result', 'Scope'], rows: [['Target FPGA', 'Arty S7-35T', 'xc7a35t-csg324-1'], ['Slices', '2,294', 'post-implementation'], ['LUTs', '3,953', 'post-implementation'], ['Flip-flops', '4,506', 'post-implementation'], ['DSPs', '42', 'post-implementation'], ['BRAMs', '33', 'post-implementation'], ['SRLs / CLBs', '14 / 0', 'reported resources'], ['URAM / latches', '0 / 0', 'reported resources'], ['Timing', 'Met', 'final implementation'], ['Total on-chip power', '≈ 3 mW', 'reported estimate']] },
      { title: 'Timing and functional validation', columns: ['Check', 'Result', 'Scope'], rows: [['Clock period required', '20.000 ns', 'Vivado constraint'], ['Post-synthesis period', '12.462 ns', 'Vivado report'], ['Post-implementation period', '13.606 ns', 'Vivado report'], ['Estimated HLS Fmax', '55.74 MHz', 'Vitis HLS synthesis'], ['Functional verification', 'PASS', 'quantized output + softmax'], ['Model path', 'INT8 Tiny1D-CNN', 'C/RTL and FPGA IP']] },
      { title: 'Model-to-hardware flow', columns: ['Stage', 'Artifact', 'Tool'], rows: [['Quantization', 'INT8 Tiny1D-CNN', 'PyTorch'], ['High-level synthesis', 'Synthesizable RTL / IP', 'Vitis HLS'], ['Integration', 'Clock, reset, control, IO', 'Vivado'], ['Implementation', 'Placed and routed FPGA design', 'Vivado'], ['Validation', 'Quantized outputs + class prediction', 'C/RTL comparison']] },
    ],
    physicalRecord: [['Target FPGA', 'Arty S7-35T · xc7a35t-csg324-1'], ['Flow', 'Vitis HLS → Vivado'], ['LUTs / FFs', '3,953 / 4,506'], ['DSPs / BRAMs', '42 / 33'], ['Post-implementation period', '13.606 ns'], ['Timing', 'Met'], ['HLS estimated Fmax', '55.74 MHz'], ['On-chip power', '≈ 3 mW']],
    visual: 'fpga',
    categories: ['AI', 'FPGA'],
  },
]

export const archiveProjects = [
  {
    year: '2026 →',
    title: 'Sparsity-aware SAR ATR accelerator',
    description: 'Current direction: PyTorch/Brevitas → Vitis HLS → Vivado → OpenROAD SKY130, with dynamic zero skipping and PE clock gating for SARDet-100K workloads.',
    tags: ['SAR', 'Sparsity', 'Brevitas', 'SKY130'],
    status: 'In progress',
  },
  {
    year: '2026',
    title: 'OpenTA1N device simulation notebook',
    description: 'A DEVSIM-based 1 nm-class PDK exploration focused on mesh convergence, compact-model behavior, and reproducible device-analysis tooling.',
    tags: ['DEVSIM', 'TCAD', 'Python'],
    status: 'Research notebook',
  },
  {
    year: '2025',
    title: 'INT8 quantization for glucose prediction',
    description: 'PyTorch static quantization with C/RTL co-simulation for a Tiny 1D-CNN trained on the DiaData continuous glucose monitoring dataset.',
    tags: ['PyTorch', 'INT8', 'DiaData'],
    status: 'Model-to-hardware',
  },
  {
    year: '2025',
    title: 'PicoRV32 stride prediction & prefetch',
    description: 'Implemented stride prediction and prefetch buffering for the PicoRV32 RISC-V processor; work accepted at ICCIIoT 2025.',
    tags: ['RISC-V', 'PicoRV32', 'Verilog'],
    status: 'Published work',
  },
  {
    year: '2024',
    title: 'Battery-less NFC plant sensor',
    description: 'A biodegradable, battery-free NFC/RFID sensor concept for wireless plant monitoring and connected precision agriculture.',
    tags: ['NFC', 'RFID', 'IoT'],
    status: 'Embedded systems',
  },
  {
    year: '2024',
    title: 'CanSat weather-monitoring satellite',
    description: 'Designed, built, and deployed an open-source weather-monitoring nano-satellite for the national CanSat competition.',
    tags: ['LoRa', 'C/C++', 'Telemetry'],
    status: 'Published work',
  },
  {
    year: '2024',
    title: 'CubeSat dipole antenna',
    description: 'High-gain dipole tape antenna for IoT PocketQube/CubeSat applications, designed and simulated in HFSS.',
    tags: ['HFSS', 'RF', 'CubeSat'],
    status: 'Published work',
  },
  {
    year: '2023',
    title: 'Connected embedded systems',
    description: 'BLDC motor monitoring, EV battery management, radiological inspection robotics, and intelligent meteorological observation systems.',
    tags: ['ESP32', 'C/C++', 'LoRa', 'Sensors'],
    status: 'Selected archive',
  },
]

export const capabilities = [
  {
    title: 'AI accelerator architecture',
    description: 'Systolic arrays, CNN and Transformer datapaths, low-precision arithmetic, memory movement, and hardware–software co-design.',
    stack: 'Gemmini · Chipyard · RISC-V · PyTorch',
  },
  {
    title: 'RTL & verification',
    description: 'Readable Verilog, interface design, functional verification, C/RTL co-simulation, synthesis constraints, and report-driven iteration.',
    stack: 'Verilog · SystemVerilog · Python · Bash · Git',
  },
  {
    title: 'ASIC implementation',
    description: 'Floorplanning, placement, CTS, routing, STA, physical verification, and PPA evaluation from RTL to GDSII.',
    stack: 'Genus · Innovus · Yosys · OpenROAD · KLayout',
  },
  {
    title: 'Embedded & connected systems',
    description: 'Low-power sensing, wireless telemetry, microcontrollers, PCB bring-up, and the system details around a useful prototype.',
    stack: 'C/C++ · ESP32 · LoRa · BLE · NFC/RFID',
  },
]

export const experience = [
  {
    period: 'Jul — Oct 2026',
    role: 'Lab Instructor & Teaching Assistant',
    org: 'USTP · NSHRDP–INSPIRE',
    description: 'Led Digital IC Design & Verification labs through RTL-to-GDSII: Genus/Innovus backend, floorplanning, placement, STA, routing, physical verification, and GDSII.',
  },
  {
    period: 'Oct 2025 — Jul 2026',
    role: 'Research Assistant',
    org: 'University of Stirling, UK · virtual',
    description: 'Worked with Dr Hazrat Ali on AI for biomedical monitoring, edge FPGA inference, and low-power ASIC-oriented accelerator design.',
  },
  {
    period: 'Jan 2024 — Feb 2026',
    role: 'Research Intern',
    org: 'GIKI, Pakistan',
    description: 'Built IoT, embedded sensing, and real-time data-acquisition systems for applied research and field-ready demonstrations.',
  },
  {
    period: 'Dec 2024 — Jul 2025',
    role: 'Research Assistant',
    org: 'South Dakota State University, USA · virtual',
    description: 'Worked with Dr Mazhar Sher on heart-failure monitoring and smart battery-less systems for agriculture and biomedical IoT.',
  },
  {
    period: 'Jan — Apr 2024',
    role: 'Leadership Fellow',
    org: 'Aspire Institute · Harvard Business School, USA',
    description: 'Developed strategic decision-making, team leadership, and problem-solving skills through a global leadership program.',
  },
  {
    period: 'Nov — Dec 2023',
    role: 'Project Delivery Lead',
    org: 'Government Post Graduate College, Abbottabad',
    description: 'Delivered an IoT environmental-monitoring device for the Botany Department, enabling real-time data collection for scientific analysis.',
  },
]

export const publications = [
  {
    year: '2026',
    type: 'Manuscript · under review',
    title: 'A DSP-Free Streaming ASIC Accelerator with Fully Pipelined Dataflow for Real-Time 1D-CNN Inference in Edge-Based Continuous Glucose Monitoring',
    authors: 'Talha Alam · H. Ali',
    venue: 'IEEE Transactions on Computational Systems for AI',
    href: 'https://doi.org/10.3233/ATDE251018',
  },
  {
    year: '2026',
    type: 'Manuscript · under review',
    title: 'Hardware-Efficient Hyperglycemic Event Prediction: A Quantized Tiny 1D-CNN for Edge-Based Continuous Glucose Monitoring',
    authors: 'Talha Alam · H. Ali',
    venue: 'Advanced Intelligent Systems · Wiley',
    href: 'https://doi.org/10.3233/ATDE251022',
  },
  {
    year: '2025',
    type: 'Accepted conference paper',
    title: 'Implementation of Stride Prediction and Prefetch Buffering for PicoRV32 RISC-V Processor',
    authors: 'N. Chalane · M. M. Khan · Talha Alam',
    venue: 'ICCIIoT 2025',
  },
  {
    year: '2025',
    type: 'Conference paper',
    title: 'Computational Cognitive Network-Based Radiological Inspection Robot for Nuclear Environment Survey',
    authors: 'A. A. M. Anik · M. Sadia · A. Tahmid · collaborators · Talha Alam',
    venue: 'MMSE 2025',
  },
  {
    year: '2025',
    type: 'Conference paper',
    title: 'Intelligent Meteorological Observation System Amid IR and Piconet Network Protocol',
    authors: 'A. A. Mamun · M. Sadia · Talha Alam · M. F. Mahmood',
    venue: 'MMSE 2025',
  },
  {
    year: '2024',
    type: 'Conference paper',
    title: 'CanSat: Design, Development, and Deployment of Open-Source Weather Monitoring Nano-Satellite',
    authors: 'Talha Alam · M. Javed · A. Rehman · A. A. Mamun',
    venue: 'ICoDT 2024',
    href: 'https://doi.org/10.1109/ICoDT262145.2024.10740189',
  },
]

export const talks = [
  {
    label: 'Poster · June 2026',
    title: 'Hyperglycaemic Event Prediction through Continuous Glucose Monitoring on Hardware Efficient Deep Learning',
    detail: '4th UK Multimodal AI Workshop · London',
    href: 'https://www.linkedin.com/feed/update/urn:li:activity:7503094299283079170/',
  },
]
