export const profile = {
  name: 'Talha Alam',
  shortName: 'TA',
  role: 'Electronics Engineer · AI Hardware',
  location: 'KPK, Pakistan',
  email: 'talhaalame.e@gmail.com',
  phone: '+92 349 9530896',
  education: 'B.Sc. Electronics Engineering · UET Peshawar · 2022–2026',
  headline: 'I design the hardware behind efficient AI.',
  subhead: 'Digital VLSI, low-precision accelerators, and complete RTL-to-GDSII systems — with the model, microarchitecture, and physical design considered together.',
  links: {
    github: 'https://github.com/talha-ee',
    linkedin: 'https://www.linkedin.com/in/talhaalam-e-e/',
    scholar: 'https://scholar.google.com/citations?user=Ue74-00AAAAJ&hl=en',
    orcid: 'https://orcid.org/0009-0007-6627-4601',
    researchgate: 'https://www.researchgate.net/profile/Talha-Alam-3',
  },
}

export const proofPoints = [
  { value: 'RTL → GDSII', label: 'design range' },
  { value: 'AI + VLSI', label: 'working intersection' },
  { value: '45–130 nm', label: 'flow experience' },
]

export const projects = [
  {
    id: 'accelclosure',
    index: '01',
    year: '2026',
    kind: 'Research system',
    title: 'AccelClosure',
    deck: 'An agentic prompt-to-GDS framework for AI accelerator exploration.',
    summary: 'Turning an architecture brief into reproducible RTL, synthesis, physical design, and measured PPA evidence on an open process.',
    detail: 'The current physically validated backend is a square, weight-stationary INT8 array on Sky130HD. AccelClosure keeps the design loop inspectable: architecture choices, generated RTL, constraints, implementation reports, and the final layout all stay connected.',
    metric: '208.95 MHz',
    metricLabel: 'fresh 8×8 post-route Fmax',
    secondary: [
      ['0 / 0 / 0', 'timing · DRC · LVS violations'],
      ['0.497935 mm²', 'fresh 8×8 area'],
      ['0.317 W', 'fresh 8×8 reported power'],
    ],
    tags: ['Sky130HD', 'INT8', 'Weight-stationary', 'OpenROAD'],
    note: 'Physical validation is reported implementation evidence, not foundry signoff. The 32×32 run is pre-layout only.',
    links: [{ label: 'Project post', href: 'https://lnkd.in/p/dGeVrmcd' }],
    figureImage: './figures/accelclosure/final-gds.png',
    visual: 'accel',
    categories: ['AI', 'ASIC', 'Research'],
  },
  {
    id: 'gemmini',
    index: '02',
    year: '2026',
    kind: 'Thesis · accelerator architecture',
    title: 'Extending Gemmini for transformer workloads',
    deck: 'A lower-cost INT8 multiplier inside a configurable RISC-V systolic array.',
    summary: 'Reworking the arithmetic at the processing-element level, then tracing the effect through 16×16, 32×32, and 64×64 Gemmini meshes.',
    detail: 'I replaced the native signed INT8 multiplier with a radix-4 Booth multiplier using single-stage stacking and hybrid 3:2/4:2 compressors, with a Kogge–Stone final adder. The design was integrated into Gemmini within Chipyard and evaluated across weight-stationary and output-stationary dataflows.',
    metric: '13.49%',
    metricLabel: 'less mapped area · 32×32 mesh',
    secondary: [
      ['13.49%', 'less area · 16×16 SKY130'],
      ['15.79%', 'fewer cells · 32×32 SKY130'],
      ['1.217 mm²', '16×16 GPDK045 footprint'],
    ],
    tags: ['Gemmini', 'Chipyard', 'RISC-V', 'Booth + compressors'],
    note: 'The 13.49% area result is a SKY130 hierarchical synthesis comparison. The 1.217 mm² figure is a separate 16×16 Cadence GDSII implementation.',
    links: [{ label: 'Gemmini / Chipyard repo', href: 'https://github.com/talha-ee/Chipyard-1.9.1-with-RISC-V-Toolchains' }, { label: 'GitHub profile', href: profile.links.github }],
    visual: 'gemmini',
    categories: ['AI', 'ASIC', 'Research'],
  },
  {
    id: 'nce',
    index: '03',
    year: '2026',
    kind: 'Mixed-precision compute',
    title: 'Neural Compute Engine',
    deck: 'Eight lanes for practical mixed-precision inference at the edge.',
    summary: 'A verified systolic/tiled GEMM and convolution engine that packs INT8, BF16, BF24, and FP32 accumulation into one controllable datapath.',
    detail: 'The NCE combines tensor memories, an AXI4-Lite control plane, and eight mixed-precision lanes. I carried the design through verification and an open SKY130 RTL-to-GDSII flow, keeping the interface and physical evidence visible alongside the datapath.',
    metric: '62 / 62',
    metricLabel: 'verification suites passed',
    secondary: [
      ['1,006', 'AXI transactions'],
      ['8.2 × 8.2 mm', 'reported chip outline'],
      ['154', 'GPIO pads'],
      ['5,999', 'vias · final layout'],
      ['0', 'detailed-routing violations'],
    ],
    tags: ['INT8', 'BF16', 'BF24', 'FP32 accumulate', 'AXI4-Lite'],
    note: 'The dimensions and routing result describe the reported SKY130 implementation and are not a claim of fabricated silicon.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7490874114795048962/' }],
    visual: 'nce',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'transformer',
    index: '04',
    year: '2026',
    kind: 'Transformer inference',
    title: 'INT4 attention systolic array',
    deck: 'A 16×16 attention tile with fixed-point softmax and a small memory-mapped wrapper.',
    summary: 'Designed around the real shape of transformer work: low-precision matrix math, reduction-heavy softmax, and a control surface that software can actually use.',
    detail: 'The accelerator was validated on attention tiles from GPT-2, DistilGPT2, and TinyBERT. The frozen standalone wrapper keeps Q/K/V matrix multiplication, fixed-point softmax, and the memory-mapped control surface in one measurable block.',
    metric: '6.821 GOPS',
    metricLabel: 'measured tile throughput',
    secondary: [
      ['1,201', 'cycles per tile'],
      ['16 × 16', 'INT4 array'],
      ['333.33 MHz', '3 ns standalone result'],
      ['286,546', 'mapped cells'],
    ],
    tags: ['INT4', 'Softmax', 'GPT-2', 'Cadence Genus'],
    note: 'The 333 MHz, 286,546-cell result is scoped to the standalone accelerator wrapper and excludes PicoRV32.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7476597886139555840/' }],
    visual: 'attention',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cnn-tapeout',
    index: '05',
    year: '2026',
    kind: 'ASIC · biomedical edge AI',
    title: 'Tiny 1D-CNN, all the way to GDSII',
    deck: 'An INT4, 16-PE inference engine for continuous glucose monitoring research.',
    summary: 'A complete arithmetic and memory path: exact signed multiplication, pipelined MACs, stationary weights, ping-pong activations, and signed saturation.',
    detail: 'The CNN_Tapeout architecture uses an exact signed INT4×INT4 Baugh–Wooley multiplier, LAS 3:2/4:2 compressors, a pipelined MAC, and a 16-PE one-dimensional MOSA/activation-systolic array. Requantization, ReLU, and activation memory are part of the same implementation story.',
    metric: '16 PEs',
    metricLabel: 'one-dimensional systolic array',
    secondary: [
      ['INT4', 'signed arithmetic'],
      ['SKY130', 'open PDK flow'],
      ['GDSII', 'RTL-to-layout scope'],
    ],
    tags: ['Baugh–Wooley', 'INT4', 'OpenROAD', 'GDSII'],
    note: 'The project is an implementation and research artifact for edge inference; GDSII is not foundry signoff.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478525419974086656/' }],
    visual: 'cnn',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cgm-asic',
    index: '06',
    year: '2026',
    kind: 'ASIC · low-power biomedical',
    title: 'High-performance Tiny 1D-CNN ASIC',
    deck: 'A low-power CGM inference core closed through an open RTL-to-GDSII flow.',
    summary: 'A research implementation that puts the full edge-AI path under the same constraint: useful inference with a small power and timing budget.',
    detail: 'The CGM accelerator was taken from quantized model assumptions through Verilog, synthesis, physical implementation, and layout inspection with SKY130, LibreLane, Yosys, OpenROAD, and KLayout.',
    metric: '0.216 mW',
    metricLabel: 'reported total power',
    secondary: [
      ['21.79 mm²', 'reported core area'],
      ['0 / 0', 'setup / hold violations'],
      ['35 ns', 'closed clock target'],
    ],
    tags: ['SKY130', 'LibreLane', 'OpenROAD', 'CGM'],
    note: 'These are reported open-flow implementation results, not fabricated-silicon measurements.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478525419974086656/' }],
    visual: 'physical',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'cnn-gpd045',
    index: '07',
    year: '2026',
    kind: 'ASIC · physical design',
    title: 'CNN systolic array accelerator',
    deck: 'A compact 45 nm implementation with timing and physical checks closed.',
    summary: 'Designed, synthesized, placed, routed, and checked as a complete GPDK045 RTL-to-GDSII exercise.',
    detail: 'The implementation uses a systolic array for convolutional workloads and was taken through Cadence Genus and Innovus. The physical report closes timing and common physical checks for the reported core.',
    metric: '166.7 MHz',
    metricLabel: 'closed implementation frequency',
    secondary: [
      ['0.164 mm²', 'core area'],
      ['64.227%', 'core density'],
      ['0', 'setup / hold / antenna violations'],
    ],
    tags: ['GPDK045', 'Genus', 'Innovus', 'Systolic array'],
    note: 'Reported implementation evidence from the 45 nm flow; it is not a fabricated-chip measurement.',
    links: [{ label: 'GitHub profile', href: profile.links.github }],
    visual: 'physical',
    categories: ['AI', 'ASIC'],
  },
  {
    id: 'tiny-cnn',
    index: '08',
    year: '2026',
    kind: 'FPGA · model-to-hardware',
    title: 'Streaming line-buffer CNN',
    deck: 'A dataflow-optimized Tiny 1D-CNN that keeps the window moving and the DSP budget at zero.',
    summary: 'Connecting PyTorch quantization to a streaming Artix-7 implementation with loop unrolling, pipelining, and a sliding-window buffer.',
    detail: 'The accelerator was developed with Vitis HLS and Vivado for real-time glucose prediction research. The microarchitecture removes DSP usage, improves the data path, and keeps the model-to-hardware assumptions explicit.',
    metric: '3×',
    metricLabel: 'latency improvement',
    secondary: [
      ['0', 'DSP blocks'],
      ['21%', 'reported power reduction'],
      ['Artix-7', 'target FPGA'],
    ],
    tags: ['Vitis HLS', 'Vivado', 'INT8', 'Dataflow'],
    note: 'The 3× and 21% figures are reported research results for the streaming implementation.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478055241054212096/' }],
    visual: 'stream',
    categories: ['AI', 'FPGA'],
  },
  {
    id: 'fpga-cgm',
    index: '09',
    year: '2026',
    kind: 'FPGA · edge inference',
    title: 'INT8 1D-CNN on Arty S7-35T',
    deck: 'A complete quantized model and custom inference accelerator for an accessible FPGA target.',
    summary: 'Training, static INT8 quantization, C/RTL co-simulation, and constrained implementation in one reproducible loop.',
    detail: 'The design maps a quantized Tiny 1D-CNN to the Arty S7-35T, with the model, RTL datapath, memory organization, and FPGA constraints treated as one system.',
    metric: '3,953',
    metricLabel: 'LUTs after implementation',
    secondary: [
      ['4,506', 'flip-flops'],
      ['42', 'DSP blocks'],
      ['33', 'BRAMs'],
    ],
    tags: ['Arty S7-35T', 'Verilog', 'INT8', 'Vivado'],
    note: 'Utilization values refer to this FPGA build and are not ASIC area figures.',
    links: [{ label: 'Project post', href: 'https://www.linkedin.com/feed/update/urn:li:activity:7478055241054212096/' }],
    visual: 'fpga',
    categories: ['AI', 'FPGA'],
  },
]

export const archiveProjects = [
  {
    year: '2026 →',
    title: 'Sparsity-aware SAR ATR accelerator',
    description: 'Current direction: PyTorch/Brevitas → Vitis HLS → Vivado → OpenROAD SKY130, with dynamic zero skipping and PE clock gating for SARDet-100K workloads.',
    tags: ['SAR', 'Sparsity', 'Brevitas', 'SKY130'],
    status: 'In progress',
  },
  {
    year: '2026',
    title: 'OpenTA1N device simulation notebook',
    description: 'A DEVSIM-based 1 nm-class PDK exploration focused on mesh convergence, compact-model behavior, and reproducible device-analysis tooling.',
    tags: ['DEVSIM', 'TCAD', 'Python'],
    status: 'Research notebook',
  },
  {
    year: '2025',
    title: 'INT8 quantization for glucose prediction',
    description: 'PyTorch static quantization with C/RTL co-simulation for a Tiny 1D-CNN trained on the DiaData continuous glucose monitoring dataset.',
    tags: ['PyTorch', 'INT8', 'DiaData'],
    status: 'Model-to-hardware',
  },
  {
    year: '2025',
    title: 'PicoRV32 stride prediction & prefetch',
    description: 'Implemented stride prediction and prefetch buffering for the PicoRV32 RISC-V processor; work accepted at ICCIIoT 2025.',
    tags: ['RISC-V', 'PicoRV32', 'Verilog'],
    status: 'Published work',
  },
  {
    year: '2024',
    title: 'Battery-less NFC plant sensor',
    description: 'A biodegradable, battery-free NFC/RFID sensor concept for wireless plant monitoring and connected precision agriculture.',
    tags: ['NFC', 'RFID', 'IoT'],
    status: 'Embedded systems',
  },
  {
    year: '2024',
    title: 'CanSat weather-monitoring satellite',
    description: 'Designed, built, and deployed an open-source weather-monitoring nano-satellite for the national CanSat competition.',
    tags: ['LoRa', 'C/C++', 'Telemetry'],
    status: 'Published work',
  },
  {
    year: '2024',
    title: 'CubeSat dipole antenna',
    description: 'High-gain dipole tape antenna for IoT PocketQube/CubeSat applications, designed and simulated in HFSS.',
    tags: ['HFSS', 'RF', 'CubeSat'],
    status: 'Published work',
  },
  {
    year: '2023',
    title: 'Connected embedded systems',
    description: 'BLDC motor monitoring, EV battery management, radiological inspection robotics, and intelligent meteorological observation systems.',
    tags: ['ESP32', 'C/C++', 'LoRa', 'Sensors'],
    status: 'Selected archive',
  },
]

export const capabilities = [
  {
    title: 'AI accelerator architecture',
    description: 'Systolic arrays, CNN and Transformer datapaths, low-precision arithmetic, memory movement, and hardware–software co-design.',
    stack: 'Gemmini · Chipyard · RISC-V · PyTorch',
  },
  {
    title: 'RTL & verification',
    description: 'Readable Verilog, interface design, functional verification, C/RTL co-simulation, synthesis constraints, and report-driven iteration.',
    stack: 'Verilog · SystemVerilog · Python · Bash · Git',
  },
  {
    title: 'ASIC implementation',
    description: 'Floorplanning, placement, CTS, routing, STA, physical verification, and PPA evaluation from RTL to GDSII.',
    stack: 'Genus · Innovus · Yosys · OpenROAD · KLayout',
  },
  {
    title: 'Embedded & connected systems',
    description: 'Low-power sensing, wireless telemetry, microcontrollers, PCB bring-up, and the system details around a useful prototype.',
    stack: 'C/C++ · ESP32 · LoRa · BLE · NFC/RFID',
  },
]

export const experience = [
  {
    period: 'Jul — Oct 2026',
    role: 'Lab Instructor & Teaching Assistant',
    org: 'USTP · NSHRDP–INSPIRE',
    description: 'Led Digital IC Design & Verification labs through RTL-to-GDSII: Genus/Innovus backend, floorplanning, placement, STA, routing, physical verification, and GDSII.',
  },
  {
    period: 'Oct 2025 — Jul 2026',
    role: 'Research Assistant',
    org: 'University of Stirling, UK · virtual',
    description: 'Worked with Dr Hazrat Ali on AI for biomedical monitoring, edge FPGA inference, and low-power ASIC-oriented accelerator design.',
  },
  {
    period: 'Jan 2024 — Feb 2026',
    role: 'Research Intern',
    org: 'GIKI, Pakistan',
    description: 'Built IoT, embedded sensing, and real-time data-acquisition systems for applied research and field-ready demonstrations.',
  },
  {
    period: 'Dec 2024 — Jul 2025',
    role: 'Research Assistant',
    org: 'South Dakota State University, USA · virtual',
    description: 'Worked with Dr Mazhar Sher on heart-failure monitoring and smart battery-less systems for agriculture and biomedical IoT.',
  },
  {
    period: 'Jan — Apr 2024',
    role: 'Leadership Fellow',
    org: 'Aspire Institute · Harvard Business School, USA',
    description: 'Developed strategic decision-making, team leadership, and problem-solving skills through a global leadership program.',
  },
  {
    period: 'Nov — Dec 2023',
    role: 'Project Delivery Lead',
    org: 'Government Post Graduate College, Abbottabad',
    description: 'Delivered an IoT environmental-monitoring device for the Botany Department, enabling real-time data collection for scientific analysis.',
  },
]

export const publications = [
  {
    year: '2026',
    type: 'Manuscript · under review',
    title: 'A DSP-Free Streaming ASIC Accelerator with Fully Pipelined Dataflow for Real-Time 1D-CNN Inference in Edge-Based Continuous Glucose Monitoring',
    authors: 'Talha Alam · H. Ali',
    venue: 'IEEE Transactions on Computational Systems for AI',
    href: 'https://doi.org/10.3233/ATDE251018',
  },
  {
    year: '2026',
    type: 'Manuscript · under review',
    title: 'Hardware-Efficient Hyperglycemic Event Prediction: A Quantized Tiny 1D-CNN for Edge-Based Continuous Glucose Monitoring',
    authors: 'Talha Alam · H. Ali',
    venue: 'Advanced Intelligent Systems · Wiley',
    href: 'https://doi.org/10.3233/ATDE251022',
  },
  {
    year: '2025',
    type: 'Accepted conference paper',
    title: 'Implementation of Stride Prediction and Prefetch Buffering for PicoRV32 RISC-V Processor',
    authors: 'N. Chalane · M. M. Khan · Talha Alam',
    venue: 'ICCIIoT 2025',
  },
  {
    year: '2025',
    type: 'Conference paper',
    title: 'Computational Cognitive Network-Based Radiological Inspection Robot for Nuclear Environment Survey',
    authors: 'A. A. M. Anik · M. Sadia · A. Tahmid · collaborators · Talha Alam',
    venue: 'MMSE 2025',
  },
  {
    year: '2025',
    type: 'Conference paper',
    title: 'Intelligent Meteorological Observation System Amid IR and Piconet Network Protocol',
    authors: 'A. A. Mamun · M. Sadia · Talha Alam · M. F. Mahmood',
    venue: 'MMSE 2025',
  },
  {
    year: '2024',
    type: 'Conference paper',
    title: 'CanSat: Design, Development, and Deployment of Open-Source Weather Monitoring Nano-Satellite',
    authors: 'Talha Alam · M. Javed · A. Rehman · A. A. Mamun',
    venue: 'ICoDT 2024',
    href: 'https://doi.org/10.1109/ICoDT262145.2024.10740189',
  },
]

export const talks = [
  {
    label: 'Poster · June 2026',
    title: 'Hyperglycaemic Event Prediction through Continuous Glucose Monitoring on Hardware Efficient Deep Learning',
    detail: '4th UK Multimodal AI Workshop · London',
    href: 'https://www.linkedin.com/feed/update/urn:li:activity:7503094299283079170/',
  },
]
